### ISSUE TITLE
Update to vue 3.2.37

### ISSUE THREAD

**Issue by devgholami** [chyj4747/vue3-golden-layout-virtualcomponent#4]
Hi! I need to use this nice library in Vue 3.2.37 with vite which affects using the golden layout. I tried to fix this, but I couldn't. I am thankful for your help in advance.

**Comment by weigao-123** [comment]
I also tried using this in Vue 3.2.37 with vite, and the following error shows: 

`Uncaught (in promise) TypeError: component.glc.setVisibility is not a function
    at handleContainerVirtualVisibilityChangeRequiredEvent (Glayout.vue:203:9)
    at container.virtualVisibilityChangeRequiredEvent (Glayout.vue:248:13)
    at ComponentContainer.setVisibility (component-container.ts:292:22)
    at ComponentItem.hide (component-item.ts:181:25)
    at Stack.init (stack.ts:182:37)
    at RowOrColumn.initContentItems (content-item.ts:380:35)
    at RowOrColumn.init (row-or-column.ts:252:14)
    at VirtualLayout.createAndInitContentItem (layout-manager.ts:682:17)
    at GroundItem.loadRoot (ground-item.ts:69:56)
    at VirtualLayout.loadLayout (layout-manager.ts:313:34)`

Then I found that component.glc is an Array of Proxy object, but it should be the Proxy object without the Array wrapper. Probably becasue internal api getCurrentInstance() of Vue 3.2.37 has modified, and then the instance?refs[ref] returns a Array of Proxy object. A temporary solution would be as follows in the Glayout.vue component:

replace
`const component = instance?.refs[ref] as GlComponent;`
with 
`const component = instance?.refs[ref] instanceof Array ? instance?.refs[ref][0] : instance?.refs[ref] as GlComponent;`
